### ISSUE TITLE
Doesn't work on termux

### ISSUE THREAD

**Issue by AleUrba08** [PineberryCode/JDNETTING#2]
I don't know why It doesn't work. It says 'fatal: destination path 'JDNETTING' already exists and is not an empty directory.' Can you help me?

**Comment by PineberryCode** [comment]
Hi 👋 
Could you provide me more details about what you were doing when you encountered that issue? Maybe you could try removing the directory `rm -rf JDNETTING` and then cloning it again into another folder.

**Comment by PineberryCode** [comment]
> Hi 👋 Could you provide me more details about what you were doing when you encountered that issue? Maybe you could try removing the directory `rm -rf JDNETTING` and then cloning it again into another folder.

Now, I understand what it is. You have wanted to re-clone the same repository. Enter the repo and follow these steps:

> Enable execute permission to `running.sh`.
> Execute `running.sh`.
> Use `jdnet`.
